print("Full Name: Mark Louisse Jardiniano")
print("Address: Isok1, Boac, Marinduque")
print("Birthday: May 21, 2002")
print("College: Marinduque State College")
print("Course: Information Technology")
print("Year & Section: 2nd year Section B")
print("My Hobbies:")
print("1. Playing Basketball")
print("2. Playing Online Games")
print("3. Reading Books")
print("4. Painting")
print("5. Skimboarding")